nav:
  - Contenu: README.md
  - Architecture: architecture.md
  - Contribution: contributing.md
  - Qualité Code: qualite_code.md
  - Test: testing.md
  - Déploiement: deployment.md
  - Claude code: claude-code.md
  - A propos doc developeur: README.md
  - Outils Documentation: documentation_tools.md
